 - name: dotfiles 
   import_playbook: dotfiles.yml
   tags: 
    - dotfiles

 - name: maven 
   import_playbook: maven.yml
   tags:
    - mvn

 - name: gradle
   import_playbook: gradle.yml
   tags:
    - gradle

 - name: vault
   import_playbook: vault.yml
   tags:
    - vault

 - name: kubectl
   import_playbook: kubectl.yml
   tags:
    - kubectl

 - name: minikube
   import_playbook: minikube.yml
   tags:
    - minikube

 - name: terraform
   import_playbook: terraform.yml
   tags:
    - terraform

 - name: keys
   import_playbook: keys.yml
   tags:
    - keys

 - name: intellij-ultimate
   import_playbook: intellij-ultimate.yml
   tags:
    - intellij-ultimate

 - name: sequel pro
   import_playbook: sequel-pro.yml
   tags:
    - sequel-pro


