---
 - local_action: stat path={{ gradle_install_dest }}
   register: gradle_exists

 - name: install gradle
   unarchive:
     src: https://downloads.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip
     dest: "{{ gradle_base_install_dest }}"
     remote_src: yes
   become: yes
   when: gradle_exists.stat.exists == False

 - name: symlink
   file:
     src: "{{ gradle_install_dest }}/bin/gradle"
     dest: "{{ gradle_link_dest }}"
     state: link
     mode: +x
   become: yes
   when: gradle_exists.stat.exists == False
