---
 - local_action: stat path={{ gradle_install_dest }}
   register: gradle_exists

 - name: install gradle
   unarchive:
     src: https://downloads.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip
     dest: "{{ gradle_base_install_dest }}"
     remote_src: yes
   when: gradle_exists.stat.exists == False

 - name: gradle env vars in bash profile
   lineinfile:
     path: ~/.bash_profile
     line: '{{ item }}' 
   with_items:
     - export PATH={{ gradle_install_dest }}/bin:$PATH 
   when: gradle_exists.stat.exists == False

