---
 - local_action: stat path={{ mvn_install_dest }}
   register: mvn_exists

 - name: download apache maven
   get_url: url=http://mirror.metrocast.net/apache/maven/maven-3/{{ mvn_version }}/binaries/apache-maven-{{ mvn_version }}-bin.tar.gz dest=/tmp/apache-maven-bin.tar.gz
   when: mvn_exists.stat.exists == False

 - name: make directory for maven
   file:
     path: "{{ mvn_base_install_dest }}"
     state: directory
   become: yes
   when: mvn_exists.stat.exists == False

 - name: untar maven
   shell: chdir=/tmp tar -zxf apache-maven-bin.tar.gz -C {{ mvn_base_install_dest }}
   become: yes
   when: mvn_exists.stat.exists == False

 - name: M2 environment variables in bash profile
   lineinfile:
     path: ~/.bash_profile
     line: '{{ item }}' 
     with_items:
       - export M2_HOME={{ mvn_install_dest }}
       - export M2=$M2_HOME/bin
       - export PATH=$M2:$PATH 
   when: mvn_exists.stat.exists == False
