- local_action: stat path=/Applications/{{ appName }}.app
  register: app_exists

- command: mkdir -p ./tmp/
  when: app_exists.stat.exists == False

- get_url: url={{ dmgURL }} dest=./tmp/{{ appName }}.dmg
  when: app_exists.stat.exists == False

- command: hdiutil attach ./tmp/{{ appNameEscaped }}.dmg -nobrowse -mountpoint ./tmp/{{ appNameEscaped }}
  when: app_exists.stat.exists == False

- shell: cp -aR ./tmp/{{ appNameEscaped }}/*.app /Applications/{{ appNameEscaped }}.app
  when: app_exists.stat.exists == False

- command: hdiutil detach ./tmp/{{ appNameEscaped }}/
  when: app_exists.stat.exists == False
